# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

permissions:
  id-token: write
  contents: read
  checks: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Load secrets
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          UPLOAD_KEYSTORE_PASSPHRASE: ${{ secrets.UPLOAD_KEYSTORE_PASSPHRASE }}
          UPLOAD_KEYSTORE_PASSWORD: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}
          UPLOAD_KEYSTORE_ALIAS: ${{ secrets.UPLOAD_KEYSTORE_ALIAS }}
        run: |
            echo $GOOGLE_SERVICES_JSON | base64 --decode > android/app/google-services.json
            echo "${{ secrets.FIREBASE_OPTIONS }}" > lib/firebase_options.dart
            echo "${{ secrets.UPLOAD_KEYSTORE }}" > android/upload-keystore.asc
            gpg -d --passphrase $UPLOAD_KEYSTORE_PASSPHRASE --batch android/upload-keystore.asc > android/upload-keystore.jks
            touch android/key.properties
            echo "storePassword=$UPLOAD_KEYSTORE_PASSWORD" >> android/key.properties
            echo "keyPassword=$UPLOAD_KEYSTORE_PASSWORD" >> android/key.properties
            echo "keyAlias=$UPLOAD_KEYSTORE_ALIAS" >> android/key.properties
            echo "storeFile=$PWD/android/upload-keystore.jks" >> android/key.properties
                
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable # or: beta, master (or main)
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Tests            # Name of the check run which will be created
          path: reports/test-results.json    # Path to test results
          reporter: flutter-json        # Format of test results
        
      - run: flutter build apk
      - run: flutter build web
